In [1]:
import numpy as np

In [2]:
myarr = np.array([1,2,3,4,5])

In [3]:
myarr

array([1, 2, 3, 4, 5])

In [4]:
type(myarr)

numpy.ndarray

In [5]:
myarr.shape

(5,)

In [6]:
myarr.size

5

In [8]:
myarr.all()

True

In [9]:
import numpy as np

In [10]:
arr = np.array((1,2,3,4,5))

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr = np.array([[1,2,3],[4,5,6]])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr.shape

(2, 3)

In [16]:
arr.size

6

In [18]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
arr.ndim

2

In [20]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [21]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [22]:
arr.size

9

In [23]:
arr.shape

(1, 3, 3)

In [26]:
arr.data

In [27]:
arr.ndim

3

In [29]:
arr = np.array([1,2,3,4,5], ndmin=5)

In [30]:
arr

array([[[[[1, 2, 3, 4, 5]]]]])

In [31]:
arr.ndim

5

In [32]:
arr.shape

(1, 1, 1, 1, 5)

In [33]:
arr.size

5

In [34]:
import numpy as np

In [35]:
arr = np.array([1,2,3,4,5])

In [36]:
arr

array([1, 2, 3, 4, 5])

In [37]:
arr[0]

1

In [38]:
arr[1]

2

In [39]:
arr[4]

5

In [40]:
arr[4] + arr[1]

7

In [41]:
print(arr)

[1 2 3 4 5]


In [42]:
print(arr[4] + arr[1])

7


In [43]:
print(arr[2] + arr[1])

5


In [44]:
print(arr[2] * arr[1])

6


# accessing elements on 2-d array

In [45]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

In [46]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
arr.ndim

2

In [48]:
print(arr[0,1])

2


In [49]:
print(1,3)

1 3


In [50]:
print(arr[1,3])

8


In [51]:
import numpy as np

arr = np.array([[[1,2,3],[2,3,1],[11,12,13]]])

In [52]:
arr

array([[[ 1,  2,  3],
        [ 2,  3,  1],
        [11, 12, 13]]])

In [53]:
arr.ndim

3

In [54]:
print(arr[0,1,1])

3


# numpy array slicing

In [55]:
import numpy as np

In [56]:
arr = np.array([1,2,3,4,5])

In [57]:
arr

array([1, 2, 3, 4, 5])

In [58]:
arr.dtype

dtype('int32')

In [59]:
arr.shape

(5,)

In [60]:
arr.size

5

In [61]:
arr[3]

4

In [62]:
arr[1:4]

array([2, 3, 4])

In [63]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [64]:
arr

array([1, 2, 3, 4, 5])

In [66]:
arr[1:5:3]

array([2, 5])

In [67]:
arr

array([1, 2, 3, 4, 5])

In [68]:
print(arr)

[1 2 3 4 5]


In [69]:
print(arr[::2])

[1 3 5]
