In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [3]:
myarr = np.array([3,4,512,2])

In [4]:
myarr

array([  3,   4, 512,   2])

In [5]:
type(myarr)

numpy.ndarray

In [6]:
myarr = np.array([14,1,2,45,50,55], np.int8)

In [7]:
myarr

array([14,  1,  2, 45, 50, 55], dtype=int8)

In [8]:
myarr = np.array([14,1,2,45,50,55], np.int32)

In [9]:
myarr

array([14,  1,  2, 45, 50, 55])

In [10]:
myarr.shape

(6,)

In [11]:
myarr = np.array([[14,1,2,45,50,55]], np.int64)

In [12]:
myarr.shape

(1, 6)

In [13]:
myarr.dtype

dtype('int64')

In [14]:
myarr[0]

array([14,  1,  2, 45, 50, 55], dtype=int64)

In [15]:
myarr[0,1]

1

In [16]:
myarr[0,3]

45

In [17]:
myarr[0,1] = 80

In [18]:
myarr

array([[14, 80,  2, 45, 50, 55]], dtype=int64)

In [19]:
myarr[0,1]

80

In [20]:
listarr = np.array([[1,2,3],[4,5,6],[11,12,13]])

In [21]:
listarr.dtype

dtype('int32')

In [22]:
listarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13]])

In [23]:
listarr.shape

(3, 3)

In [24]:
listarr.size

9

In [25]:
zeroes = np.zeros((2,5))

In [26]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
zeroes.dtype

dtype('float64')

In [28]:
zeroes.shape

(2, 5)

In [29]:
zeroes.size

10

In [30]:
rng = np.arange(16)

In [31]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
type(rng)

numpy.ndarray

In [33]:
rng.dtype

dtype('int32')

In [34]:
rng.shape

(16,)

In [35]:
rng.size

16

In [36]:
lspace = np.linspace(1,5,10)

In [37]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [38]:
lspace.size

10

In [40]:
emp = np.empty((4,6))

In [41]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511562e-306, 6.23055651e-307,
        7.56599128e-307, 1.24610587e-306, 1.24610723e-306],
       [1.42418172e-306, 2.04712906e-306, 7.56589622e-307,
        1.11258277e-307, 8.90111708e-307, 1.42410974e-306]])

In [42]:
emp.size

24

In [43]:
emp.shape

(4, 6)

In [44]:
emp.dtype

dtype('float64')

In [46]:
emp_like = np.empty_like(lspace)

In [47]:
emp_like

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
ide = np.identity(45)

In [49]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [50]:
ide.shape

(45, 45)

In [51]:
ide.size

2025

In [52]:
arr = np.arange(99)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [54]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
arr = arr.ravel()

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
arr.shape

(99,)

In [1]:
import numpy as np

In [ ]:
arr = np.array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
a.size

3

In [7]:
a.dtype

dtype('int32')

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])

In [11]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Numpy array occure less memory than list

In [14]:
import numpy as np

import time
import sys

S = range(1000) # list

print(sys.getsizeof(5)*len(S))  

D = np.arange(1000) # numpy array

print(D.size*D.itemsize)

28000
4000


# Numpy array is more faster and convenient than list

In [16]:
import numpy as np

import time

import sys

SIZE = 1000

L1 = range(SIZE)
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()

result = [(x,y) for x,y in zip(L1,L2)]  # sumation of 2 lists

print((time.time() - start)*1000)

start = time.time()

result = A1 + A2   # numpy array is more convenient

print((time.time() - start)*1000)

32.99975395202637
11.000394821166992


# Numpy operations

- Find the dimension of the Arrays
- Find The byte size of each element
- Find the data type of the element

### how to check dimension of array

In [17]:
import numpy as np

a = np.array([(1,2,3,4),(5,6,7,8)])

print(a)
print(a.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [21]:
import numpy as np

b = np.array([1,2,3,4])

print(b)
print(b.ndim)

[1 2 3 4]
1


### how to find byte size of each element

In [22]:
import numpy as np

a = np.array([1,2,3]) # here each element occupies 4 bytes size

print(a)
print(a.itemsize)

[1 2 3]
4


# size & shape

In [23]:
import numpy as np

a = np.array([1,2,3,4,5])

print(a)
print(a.size)

[1 2 3 4 5]
5


In [24]:
a.shape

(5,)

In [30]:
import numpy as np

a = np.array([(1,2,3),(11,12,13)])
print(a.size)
print(a.shape)
print(a.dtype)


6
(2, 3)
int32


# reshape operation

In [33]:
import numpy as np

a = np.array([(1,2,3,4),(11,12,13,14)])

print(a)
print(a.reshape(4,2))

[[ 1  2  3  4]
 [11 12 13 14]]
[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a*b)



[ 5 12 21 32]
